### PR TITLE
Bsp led drivers and example

### PR DESCRIPTION
**Pull request by ecruzolivera**
the driver is a based on the  [stm32f407g-disc](https://github.com/stm32-rs/stm32f407g-disc/blob/master/src/led.rs) repo

### CODE REVIEW

**Comment by ecruzolivera** [comment]
Hi @therealprof  have you been able to review this PR?

**Comment by therealprof** [comment]
Well, I didn't even see it there due to being closed. ;)

**Review by therealprof — APPROVED** [review]
Looks good, thanks!

**Comment by ecruzolivera** [comment]
yes, i think that I just make at mistake when creating the PR and delete the branch, that close the PR and create the confusion. Sorry for that, and thanks for accept the PR.

**Pull request merged**
